.TH DLM_CONTROLD 8 2012-04-05 dlm dlm

.SH NAME
dlm_controld \- dlm cluster control daemon

.SH SYNOPSIS
.B dlm_controld
[OPTIONS]

.SH DESCRIPTION
The kernel dlm requires a user daemon to manage lockspace membership.
dlm_controld manages lockspace membership using corosync cpg groups,
and translates membership changes into dlm kernel recovery events.
dlm_controld also manages posix locks for cluster file systems using
the dlm.

.SH OPTIONS
Command line options override a corresponding setting in
.BR dlm.conf (5).
.br
For default settings, see dlm_controld -h.

.B --daemon_debug | -D
        enable debugging to stderr and don't fork

.B --foreground
        don't fork

.B --log_debug | -K
        enable kernel dlm debugging messages

.B --protocol | -r
.I str
        dlm kernel lowcomms protocol: tcp, sctp, detect

.B --debug_logfile | -L
        write debugging to log file

.B --enable_plock | -p
0|1
        enable/disable posix lock support for cluster fs

.B --plock_debug | -P
        enable plock debugging

.B --plock_rate_limit | -l
.I int
        limit rate of plock operations (0 for none)

.B --plock_ownership | -o
0|1
        enable/disable plock ownership

.B --drop_resources_time | -t
.I int
        plock ownership drop resources time (milliseconds)

.B --drop_resources_count | -c
.I int
        plock ownership drop resources count

.B --drop_resources_age | -a
.I int
        plock ownership drop resources age (milliseconds)

.B --post_join_delay | -j
.I int
        seconds to delay fencing after cluster join

.B --enable_fencing | -f
0|1
        enable/disable fencing

.B --enable_concurrent_fencing
0|1
        enable/disable concurrent fencing

.B --enable_startup_fencing | -s
0|1
        enable/disable startup fencing

.B --enable_quorum_fencing | -q
0|1
        enable/disable quorum requirement for fencing

.B --enable_quorum_lockspace
0|1
        enable/disable quorum requirement for lockspace operations

.B --fence_all
.I str
        fence all nodes with this agent

.B --unfence_all
        enable unfencing self with fence_all agent

.B --help | -h
        print this help, then exit

.B --version | -V
        Print program version information, then exit

.SH SEE ALSO
.BR dlm_tool (8),
.BR dlm.conf (5)

